name: Terraform Destroy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TF_VAR_s3_bucket_region }}

      - name: Initialize Terraform
        run: terraform init "-backend-config=bucket=***" "-backend-config=region=***" "-backend-config=dynamodb_table=***" "-backend-config=encrypt=true"


      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      - name: Clean Up
        if: always()
        run: |
          terraform state rm \*
          rm -rf .terraform
          rm -f .terraform.lock.hcl

      - name: Set output
        run: echo "my_output_name=some_value" >> $GITHUB_ENV
